version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

workflows:
  build-qtads-linux:
    when:
      equal: ['qtads-linux', << pipeline.parameters.GHA_Action >>]
    jobs:
      - qtads-linux:
          name: 'QTads Linux arm64v8'
          docker_image: 'realnc/qtads-build:linux-arm64v8'
          from_arch: 'arm64v8'
          appimage_arch: 'aarch64'
          shell_wrapper: '/usr/bin/linux64'
          context:
            - global-org
      - qtads-linux:
          name: 'QTads Linux arm32v7'
          docker_image: 'realnc/qtads-build:linux-arm32v7'
          from_arch: 'arm32v7'
          appimage_arch: 'armhf'
          shell_wrapper: '/usr/bin/linux32'
          context:
            - global-org

  build-hugor-linux:
    when:
      equal: ['hugor-linux', << pipeline.parameters.GHA_Action >>]
    jobs:
      - hugor-linux:
          name: 'Hugor Linux arm64v8'
          docker_image: 'realnc/hugor-build:linux-arm64v8'
          from_arch: 'arm64v8'
          context:
            - global-org
      - hugor-linux:
          name: 'Hugor Linux arm32v7'
          docker_image: 'realnc/hugor-build:linux-arm32v7'
          from_arch: 'arm32v7'
          context:
            - global-org

  build-dosbox-core-linux:
    when:
      equal: ['dosbox-core-linux', << pipeline.parameters.GHA_Action >>]
    jobs:
      - dosbox-core-linux:
          name: 'DOSBox-core Linux arm64v8'
          docker_image: 'realnc/dosbox-core-build:linux-arm64v8'
          from_arch: 'arm64v8'
          shell_wrapper: '/usr/bin/linux64'
          context:
            - global-org
      - dosbox-core-linux:
          name: 'DOSBox-core Linux arm32v7'
          docker_image: 'realnc/dosbox-core-build:linux-arm32v7'
          from_arch: 'arm32v7'
          shell_wrapper: '/usr/bin/linux32'
          context:
            - global-org

jobs:
  qtads-linux:
    parameters:
      docker_image:
        type: string
      from_arch:
        type: string
      appimage_arch:
        type: string
      shell_wrapper:
        type: string

    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
    environment:
      DOCKER_BUILDKIT: 1

    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            cd qtads/linux
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build \
                --progress plain \
                -t << parameters.docker_image >> \
                --platform linux/arm64 \
                --cache-from << parameters.docker_image >> \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --build-arg FROM_ARCH=<< parameters.from_arch >> \
                --build-arg APPIMAGE_ARCH=<< parameters.appimage_arch >> \
                --build-arg SHELL_WRAPPER=<< parameters.shell_wrapper >> \
                .
            docker push << parameters.docker_image >>

  hugor-linux:
    parameters:
      docker_image:
        type: string
      from_arch:
        type: string

    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
    environment:
      DOCKER_BUILDKIT: 1

    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            cd hugor/linux
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build \
                --progress plain \
                -t << parameters.docker_image >> \
                --platform linux/arm64 \
                --cache-from << parameters.docker_image >> \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --build-arg FROM_ARCH=<< parameters.from_arch >> \
                .
            docker push << parameters.docker_image >>
            docker logout

  dosbox-core-linux:
    parameters:
      docker_image:
        type: string
      from_arch:
        type: string
      shell_wrapper:
        type: string

    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
    environment:
      DOCKER_BUILDKIT: 1

    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            cd dosbox-core/linux
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker build \
                --progress plain \
                -t << parameters.docker_image >> \
                --platform linux/arm64 \
                --cache-from << parameters.docker_image >> \
                --build-arg BUILDKIT_INLINE_CACHE=1 \
                --build-arg FROM_ARCH=<< parameters.from_arch >> \
                --build-arg SHELL_WRAPPER=<< parameters.shell_wrapper >> \
                .
            docker push << parameters.docker_image >>
