version: 2.1

workflows:
  build-docker-images:
    jobs:
      - qtads-linux-arm:
          filters:
            branches:
              only:
                - 'circleci/qtads-linux-arm'
      - hugor-linux-arm:
          filters:
            branches:
              only:
                - 'circleci/hugor-linux-arm'
      - dosbox-core-linux-arm:
          filters:
            branches:
              only:
                - 'circleci/dosbox-core-linux-arm'

jobs:
  qtads-linux-arm:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
    environment:
      DOCKER_BUILDKIT: 1

    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            cd qtads/linux-arm
            docker build \
                --progress plain \
                -t realnc/qtads-build:linux-arm64 \
                --platform linux/arm64 \
                --build-arg FROM_ARCH=arm64v8 \
                --build-arg APPIMAGE_ARCH=aarch64 \
                --build-arg SHELL_WRAPPER=/usr/bin/linux64 \
                .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push realnc/qtads-build:linux-arm64

  hugor-linux-arm:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
    environment:
      DOCKER_BUILDKIT: 1

    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            cd hugor/linux-arm
            docker build \
                --progress plain \
                -t realnc/hugor-build:linux-arm64 \
                --platform linux/arm64 \
                --build-arg FROM_ARCH=linux-arm64 \
                .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push realnc/hugor-build:linux-arm64

  dosbox-core-linux-arm:
    resource_class: arm.medium
    machine:
      image: ubuntu-2004:current
    environment:
      DOCKER_BUILDKIT: 1

    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            cd dosbox-core/linux
            docker build \
                --progress plain \
                -t realnc/dosbox-core-build:linux-arm64 \
                --platform linux/arm64 \
                --build-arg FROM_ARCH=arm64v8 \
                --build-arg SHELL_WRAPPER=/usr/bin/linux64 \
                .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push realnc/dosbox-core-build:linux-arm64
