name: DOSBox-core MXE x64

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'dosbox-core/mxe/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE_NAME: realnc/dosbox-core-build:mxe-x64

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd dosbox-core/mxe
          docker build \
            --progress plain \
            -t ${IMAGE_NAME} \
            --platform linux/amd64 \
            --cache-from ${IMAGE_NAME} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg DOCKER_MXE_TARGET='x86_64-w64-mingw32.static' \
            .
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push ${IMAGE_NAME}
