name: DOSBox-core Linux x64

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - '!circleci/**'
    paths:
      - 'dosbox-core/linux/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd dosbox-core/linux
          docker build \
            --progress plain \
            -t realnc/dosbox-core-build:linux-x64 \
            --platform linux/amd64 \
            --build-arg FROM_ARCH=amd64 \
            --build-arg SHELL_WRAPPER=/usr/bin/linux64 \
            .
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push realnc/dosbox-core-build:linux-x64
