name: DOSBox-core MXE x86

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'dosbox-core/mxe/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd dosbox-core/mxe
          docker build \
            --progress plain \
            -t realnc/dosbox-core-build:mxe-x86 \
            --platform linux/amd64 \
            --build-arg DOCKER_MXE_TARGETS='i686-w64-mingw32.static' \
            .
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push ${{ secrets.DOCKERHUB_USER }}/dosbox-core-build:mxe-x86
