name: DOSBox-core MXE x86

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'dosbox-core/mxe/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE_NAME: realnc/dosbox-core-build:mxe-x86

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          cd dosbox-core/mxe
          docker build \
            --progress plain \
            -t ${IMAGE_NAME} \
            --platform linux/amd64 \
            --cache-from ${IMAGE_NAME} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg DOCKER_MXE_TARGET='i686-w64-mingw32.static' \
            .
          docker push ${IMAGE_NAME}

      - name: Docker logout
        if: always()
        run: docker logout
