name: DOSBox-core Linux x64

on:
  push:
    branches:
      - master
    paths:
      - 'dosbox-core/linux-x64/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd dosbox-core/linux-x64
          docker build \
            -t realnc/dosbox-core-build:linux-x64 \
            --platform linux/amd64 \
            .
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push realnc/dosbox-core-build:linux-x64
