name: Hugor Linux x64

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - '!circleci/**'
    paths:
      - 'hugor/linux/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE_NAME: realnc/hugor-build:linux-x64

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd hugor/linux
          docker build \
            --progress plain \
            -t ${IMAGE_NAME} \
            --platform linux/amd64 \
            --cache-from ${IMAGE_NAME} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg FROM_ARCH=linux-x64 \
            --build-arg APPIMAGE_ARCH=x86_64 \
            .
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          docker push ${IMAGE_NAME}
