name: Hugor Linux CircleCI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'hugor/linux/Dockerfile'

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        id: 'hugor-linux'
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
