name: Hugor Linux x64

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'hugor/linux/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE_NAME: realnc/hugor-build:linux-x64

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
          cd hugor/linux
          docker build \
            --progress plain \
            -t ${IMAGE_NAME} \
            --platform linux/amd64 \
            --cache-from ${IMAGE_NAME} \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg FROM_ARCH=linux-x64 \
            .
          docker push ${IMAGE_NAME}

      - name: Docker logout
        if: always()
        run: docker logout
