name: QTads Linux CircleCI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'qtads/linux/Dockerfile'

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI
        id: 'qtads-linux'
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
